# Generated by Django 2.2.11 on 2020-04-18 03:09

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import serviFacilApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviFacilApp', '0002_auto_20200408_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', djongo.models.fields.EmbeddedField(model_container=serviFacilApp.models.Direccion, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviFacilApp.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviFacilApp.Empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='tipouser',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='tipouser',
            name='descripcion',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.CharField(max_length=150)),
                ('servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviFacilApp.Servicio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviFacilApp.Usuarios')),
            ],
        ),
    ]
