# Generated by Django 2.2.11 on 2020-04-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviFacilApp', '0002_auto_20200419_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='turno',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviFacilApp.Persona'),
            preserve_default=False,
        ),
    ]
