# Generated by Django 2.2.11 on 2020-04-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('serviFacilApp', '0003_auto_20200419_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='persona',
        ),
        migrations.AddField(
            model_name='empresa',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profile'),
        ),
        migrations.AddField(
            model_name='turno',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profile'),
            preserve_default=False,
        ),
    ]
